package win.yulongsun.jfinal_demo.model;

import win.yulongsun.jfinal_demo.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User();

    public User findByName(String user_name) {
        return findFirst("SELECT * FROM `user` WHERE user_name=?", user_name);
    }
}
